language: ruby
rvm:
  - 2.6.4
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rake test
services:
  - postgresql
notifications:
  email: false